volumes:
  postgres_identity_data:
  postgres_players_data:
  postgres_ratings_data:
  frontend_node_modules:

services:
  frontend.dev:
    container_name: frontend.dev
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm i && npm run dev -- -H 0.0.0.0 -p 3000"
    environment:
      BACKEND_GATEWAY_URL: "http://backend.gateway:3000"
    ports:
      - "${FRONTEND_DEV_PORT}:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
  
  postgres.identity:
    container_name: postgres.identity
    image: postgres:18.1
    environment:
      POSTGRES_USER: ${POSTGRES_IDENTITY_USER}
      POSTGRES_PASSWORD: ${POSTGRES_IDENTITY_PASSWORD}
      POSTGRES_DB: ${POSTGRES_IDENTITY_DATABASE}
    volumes:
      - postgres_identity_data:/var/lib/postgresql

  postgres.players:
    container_name: postgres.players
    image: postgres:18.1
    environment:
      POSTGRES_USER: ${POSTGRES_PLAYERS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PLAYERS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PLAYERS_DATABASE}
    volumes:
      - postgres_players_data:/var/lib/postgresql

  postgres.ratings:
    container_name: postgres.ratings
    image: postgres:18.1
    environment:
      POSTGRES_USER: ${POSTGRES_RATINGS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_RATINGS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_RATINGS_DATABASE}
    volumes:
      - postgres_ratings_data:/var/lib/postgresql
  
  backend.gateway:
    container_name: backend.gateway
    image: ${BACKEND_GATEWAY_IMAGE}
    build:
      context: .
      dockerfile: Backend.Gateway.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:3000
      Destination__IdentityUrl: "http://backend.identity:3000"
      Destination__PlayersUrl: "http://backend.players:3000"
      Destination__RatingReasonsUrl: "http://backend.ratings:3000"
      Destination__VotesUrl: "http://backend.ratings:3000"
      Jwt__CookieName: ${JWT_COOKIE_NAME}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_KEY}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
    ports:
      - "${BACKEND_GATEWAY_PORT}:3000"

  backend.identity:
    container_name: backend.identity
    image: ${BACKEND_IDENTITY_IMAGE}
    build:
      context: .
      dockerfile: Backend.Identity.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:3000
      Jwt__CookieName: ${JWT_COOKIE_NAME}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_KEY}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Db__Connection: >
        Host=postgres.identity;
        Port=5432;
        Username=${POSTGRES_IDENTITY_USER};
        Password=${POSTGRES_IDENTITY_PASSWORD};
        Database=${POSTGRES_IDENTITY_DATABASE}
      Admin__Login: ${ADMIN_LOGIN}
      Admin__Password: ${ADMIN_PASSWORD}
    restart: on-failure

  backend.players:
    container_name: backend.players
    image: ${BACKEND_PLAYERS_IMAGE}
    build:
      context: .
      dockerfile: Backend.Players.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:3000
      Jwt__CookieName: ${JWT_COOKIE_NAME}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_KEY}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Db__Connection: >
        Host=postgres.players;
        Port=5432;
        Username=${POSTGRES_PLAYERS_USER};
        Password=${POSTGRES_PLAYERS_PASSWORD};
        Database=${POSTGRES_PLAYERS_DATABASE}
    restart: on-failure
    
  backend.ratings:
    container_name: backend.ratings
    image: ${BACKEND_RATINGS_IMAGE}
    build:
      context: .
      dockerfile: Backend.Ratings.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:3000
      Jwt__CookieName: ${JWT_COOKIE_NAME}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_KEY}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Db__Connection: >
        Host=postgres.ratings;
        Port=5432;
        Username=${POSTGRES_RATINGS_USER};
        Password=${POSTGRES_RATINGS_PASSWORD};
        Database=${POSTGRES_RATINGS_DATABASE}
    restart: on-failure