volumes:
  postgres_identity_data:
  postgres_players_data:

services:
  postgres.identity:
    container_name: postgres.identity
    image: postgres:18.1
    environment:
      POSTGRES_USER: ${POSTGRES_IDENTITY_USER}
      POSTGRES_PASSWORD: ${POSTGRES_IDENTITY_PASSWORD}
      POSTGRES_DB: ${POSTGRES_IDENTITY_DATABASE}
    volumes:
      - postgres_identity_data:/var/lib/postgresql

  postgres.players:
    container_name: postgres.players
    image: postgres:18.1
    environment:
      POSTGRES_USER: ${POSTGRES_PLAYERS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PLAYERS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PLAYERS_DATABASE}
    volumes:
      - postgres_players_data:/var/lib/postgresql
  
  backend.gateway:
    container_name: backend.gateway
    image: ${BACKEND_GATEWAY_IMAGE}
    build:
      context: .
      dockerfile: Backend.Gateway.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:3000
      Destination__IdentityUrl: "http://backend.identity:3000"
      Destination__PlayersUrl: "http://backend.players:3000"
      Jwt__CookieName: ${JWT_COOKIE_NAME}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_KEY}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
    ports:
      - "${BACKEND_GATEWAY_PORT}:3000"

  backend.identity:
    container_name: backend.identity
    image: ${BACKEND_IDENTITY_IMAGE}
    build:
      context: .
      dockerfile: Backend.Identity.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:3000
      Jwt__CookieName: ${JWT_COOKIE_NAME}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_KEY}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Db__Connection: >
        Host=postgres.identity;
        Port=5432;
        Username=${POSTGRES_IDENTITY_USER};
        Password=${POSTGRES_IDENTITY_PASSWORD};
        Database=${POSTGRES_IDENTITY_DATABASE}
    restart: on-failure

  backend.players:
    container_name: backend.players
    image: ${BACKEND_PLAYERS_IMAGE}
    build:
      context: .
      dockerfile: Backend.Players.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:3000
      Jwt__CookieName: ${JWT_COOKIE_NAME}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_KEY}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Db__Connection: >
        Host=postgres.players;
        Port=5432;
        Username=${POSTGRES_PLAYERS_USER};
        Password=${POSTGRES_PLAYERS_PASSWORD};
        Database=${POSTGRES_PLAYERS_DATABASE}
    restart: on-failure